env: dev

storage:
  pdo:
    dns: $env(DB_PDO_DNS)
    username: $env(DB_PDO_USERNAME)
    password: $env(DB_PDO_PASSWORD)
  migration-directory: $env(STORAGE_MIGRATION_DIRECTORY)
  entity-directory: $env(STORAGE_ENTITY_DIRECTORY)

php-formatter:
  validator:
    path-to-php: $env(PATH_TO_PHP)
